<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Usuarios extends GenericAPI
{
    public function __construct()
    {
        parent::__construct();
        $this->model = $this->load->model('UsuariosModel');
    }

    public function index()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}